# version: 2
# ethernets:
#   ens3:
#     dhcp4: true
version: 2
ethernets:
  ens3:
    addresses:
      - 192.168.2.52/24
      - 192.168.2.53/24
    gateway4: 192.168.2.1
    nameservers:
      addresses:
        - 8.8.8.8