---
- hosts: master
  become: true
  tasks:
  - name: Add bitnami chart repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: "https://charts.bitnami.com/bitnami"
      binary_path: "/usr/local/bin/helm"
    become: false

  - name: Add ingress-nginx chart repo
    kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: "https://kubernetes.github.io/ingress-nginx"
      binary_path: "/usr/local/bin/helm"
    become: false

  - name: Values for Metal LB
    ansible.builtin.copy:
      src: ./helm-values/metal-lb-values.yaml
      dest: /home/ubuntu/metal-lb-values.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Values for ingress-nginx
    ansible.builtin.copy:
      src: ./helm-values/ingress-nginx-values.yaml
      dest: /home/ubuntu/ingress-nginx-values.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Deploy Metal LB chart using values files on target
    kubernetes.core.helm:
      name: metal-lb
      chart_ref: bitnami/metallb
      chart_version: 2.5.14
      release_namespace: kube-system
      binary_path: "/usr/local/bin/helm"
      kubeconfig: "/home/ubuntu/.kube/config"
      values_files:
        - /home/ubuntu/metal-lb-values.yaml
    become: false

  - name: Deploy ingress-nginx chart using values files on target
    kubernetes.core.helm:
      name: ingress-nginx
      chart_ref: ingress-nginx/ingress-nginx
      chart_version: 4.0.13
      release_namespace: kube-system
      binary_path: "/usr/local/bin/helm"
      kubeconfig: "/home/ubuntu/.kube/config"
      values_files:
        - /home/ubuntu/ingress-nginx-values.yaml
    become: false
